# Code Quality check
# Uses flake8 for lint - to make it right we can use black package to format python code
  # pip install black
  # black app.py [format in such order that it passes lint step]
# Uses Bandit for SAST

name: Code Quality

# runs when code pushes in the main
on:
    workflow_call:

jobs:
    linter:
        name: SAST & Lint
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11","3.12","3.13"]
        steps:

            # code copy from repo to agent
            - name: checkout code
              uses: actions/checkout@v4

            # set up python
            - name: setup python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            # install all the required packages
            - name: install packages
              run: pip install -r requirements.txt
            
            # installing flake 8 to perform linting
            - name: linter install
              run: pip install flake8 
            
            # check lint
            - name: scan code for syntax
              run: flake8 app.py
            
            # Run SAST
            - name: run SAST
              run: bandit -r app.py