# Scan the Dockerfile file to check issue & CVEs [Vernabilities]
# uses handolint

name: Docker lint

on:
    workflow_dispatch:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: validate dockerfile handolint 
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: 'Dockerfile'

