# Scan the Dockerfile file to check issue & CVEs [Vernabilities]
# uses handolint

name: Docker lint

on:
    workflow_call:

jobs:
    validate-dockerfile:
        name: Hadolint Dockerfile
        runs-on: ubuntu-latest
        steps:

            # code copy from repo to agent
            - name: checkout code
              uses: actions/checkout@v4

            # Action for handolint
            - name: validate dockerfile handolint 
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: 'Dockerfile'

