# To detects secrets Leaks in API Keys/ sensitive data/ credentails.
# Uses - Gitleaks actions

name: Secrets Scan

on:
    workflow_dispatch:

jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:

         - name: code checkout
           uses: actions/checkout@v6
           with:
             fetch-depth: 0     # it means to see the previos commits also if there any leaks

         - name: gitleaks 
           uses: gitleaks/gitleaks-action@v3
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # it is generated automatically by github.
              GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.